### PR TITLE
support coustom popup body

### PR DESCRIPTION
**Pull request by taixw2**

### CODE REVIEW

**Comment by carsonwah** [comment]
I think for custom body, we can use `renderPopupContent()` instead of `renderPopupContent({ appIconSource, appTitle, timeText, title, body })`. What do you think?

**Comment by carsonwah** [comment]
I think your approach is good. Just ignore my previous comment.

**Comment by taixw2** [comment]
Yes, The parameters are passed through the show method, so if you don't pass the parameters back to it, you may need to write some additional methods to get the parameters.

**Comment by taixw2** [comment]
I wonder if the shadow style can be separated from the animation style, because I need to modify the shadow 😅

**Comment by carsonwah** [comment]
@taixw2 You may try removing the shadow and radius from `<Animated.View>`, and put it into:

```js
<Animated.View
        style={getAnimatedContainerStyle({containerSlideOffsetY, containerDragOffsetY, containerScale})}
        {...this._panResponder.panHandlers}>
        <TouchableWithoutFeedback onPress={onPressAndSlideOut}>
          <View>  // <-- put style HERE
```

I haven't try this yet, but in this way, everyone can customize the shadow using their own custom body.

**Comment by carsonwah** [comment]
Since I have merged #20. Could you also update the typescript typings for the new prop?

Thanks so much for the contribution and sorry for the late replies.

**Comment by taixw2** [comment]
@carsonwah  I have added the corresponding type definition and added style prop.

**Comment by carsonwah** [comment]
I think we can let user customize the whole popup body. So, `style` prop may not be very useful.

I would propose something like:

```js
<Animated.View
        style={getAnimatedContainerStyle({containerSlideOffsetY, containerDragOffsetY, containerScale})}
        {...this._panResponder.panHandlers}>
        <TouchableWithoutFeedback onPress={onPressAndSlideOut}>
          <View>  // No style here
            {this.renderPopupContent()}
          </View>
        </TouchableWithoutFeedback>
      </Animated.View>
```

```js
renderPopupContent() {
    const { appIconSource, appTitle, timeText, title, body } = this.state;
    const { renderPopupContent } = this.props;
    if (renderPopupContent) {
      return renderPopupContent({ appIconSource, appTitle, timeText, title, body });
    }

    return (
      <View style={styles.popupContentContainer}>  // <-- Moved here, i.e. show shadow only for default popup
```

I cannot commit to your branch, so if you would like to, I can merge this PR first and add amendments.

**Comment by taixw2** [comment]
Agree, your approach is better.

**Comment by carsonwah** [comment]
Merged. Thanks for the contribution!

**Pull request merged**
