### PR TITLE
Specify slide out time, TypeScript typings

### PR DESCRIPTION
**Pull request by danielholmes**
Apologies for the multiple updates in one - I'll be happy to pick them apart individually if you're only interested in some. Updates here include:

 - Ability to pass a `slideOutTime` to the `show` method
 - Ability to override any of the styles via an optional style `prop`
 - TypeScript typings

Let me know your thoughts and if you want any modifications.

### CODE REVIEW

**Comment by carsonwah** [comment]
Sorry for the late reply and thanks for the PR!

slideOutTime, linting and typescript are all good. Great job! For the style part, I think there are too many customization props in this way. It will be cleaner and more intuitive if we let user pass their custom components instead of styling props. Let me know what you think.

**Comment by danielholmes** [comment]
@carsonwah Yea that sounds good to me. How granular were you thinking? e.g. optional `ContentTitle`, `ContentText`, `HeaderTime` components. Or just a custom component that goes inside the `<TouchableWithoutFeedback` ? Or maybe a [renderProp](https://reactjs.org/docs/render-props.html) style approach

**Comment by carsonwah** [comment]
I think we can take the approach from another PR https://github.com/carsonwah/react-native-push-notification-popup/pull/17. It takes a `renderPopupContent` function prop.

**Comment by danielholmes** [comment]
@carsonwah I've removed the custom styling/rendering from this PR - I didn't realise there was another open, so I'll leave that task to #17

**Comment by carsonwah** [comment]
@danielholmes Merged. Thanks so much for the contribution. I will release a new version asap, maybe together with #17.

**Pull request merged**
